name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: |
        go test -v ./src/...
        
  build:
    name: Build for ${{ matrix.os }}/${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
          - os: windows
            arch: 386
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: linux
            arch: arm
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin/vpn-client-${{ matrix.os }}-${{ matrix.arch }} src/main.go

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vpn-client-${{ matrix.os }}-${{ matrix.arch }}
        path: bin/vpn-client-${{ matrix.os }}-${{ matrix.arch }}*
        
  release:
    name: Create Release
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          vpn-client-windows-amd64/*
          vpn-client-windows-386/*
          vpn-client-linux-amd64/*
          vpn-client-linux-arm64/*
          vpn-client-linux-arm/*
          vpn-client-darwin-amd64/*
          vpn-client-darwin-arm64/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}